---
blank_issues_enabled: false
contact_links:
  - name: Android Studio and Gradle issues
    url: https://developer.android.com/studio/report-bugs
    about: >
      Issues with Android Studio or the Android Gradle Plugin are not handled by
      this team and must be filed against the Android Studio team. Android
      Studio and AGP bugs filed in this bug tracker will be closed and you'll be
      asked to refile them with Android Studio.
  - name: Android OS issues, new NDK API requests
    url: https://source.android.com/setup/contribute/report-bugs
    about: >
      Device and OS issues (typically) cannot be fixed in the NDK. Sometimes we
      can add workarounds in the NDK, in which case you can file a feature
      request here, but you should also report the bug against the OS so it can
      be fixed in future versions.

      **Do not use the NDK component.** That will just bring you back here. You
      almost always want the Framework component for this type of bug.
  - name: Questions
    url: https://github.com/android/ndk/discussions
    about: >
      If you have a question about the NDK that isn't covered by one of the
      sections above, ask in the GitHub Discussion forum. If your question is
      "Can you confirm if this is a bug?", go ahead and file it as a bug :)

      Note that we generally can't answer questions about Android APIs, Android
      Studio, or the Android Gradle Plugin. For those questions, file a
      Documentation, Framework or Studio bug using the link above.
