---
name: Feature request
description: >
  Feature requests for the NDK. **Not for Android APIs, Gradle, or Android
  Studio features.**
title: "[FR]"
labels: enhancement
body:
  - type: textarea
    attributes:
      label: Description
      description: >
        Describe the new feature, and how it would help. Include any
        alternatives or additional context that might be helpful.
